"""Atlas tokens: one source, three consumers.

    python menu/pipeline/atlas_tokens.py [--header PATH]

Reads the :root custom properties of the chosen concept's tokens.css
(menu/concepts/reunification-2026-10-06/c-atlas/tokens.css) and writes
  menu/atlas/tokens.json                  every consumer's data (launcher, tools)
  melee/pc/platform/gw_ui_tokens.h        the C header the host includes (AT_C_*, AT_PX_*, AT_MS_*)
Colours are 0xRRGGBBAA. Nothing here is hand-edited downstream.
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)  # menu/
SRC = os.path.join(ROOT, "concepts", "reunification-2026-10-06", "c-atlas", "tokens.css")
OUT_JSON = os.path.join(ROOT, "atlas", "tokens.json")
DEFAULT_HEADER = os.path.join(os.path.dirname(ROOT), "melee", "pc", "platform", "gw_ui_tokens.h")

VAR = re.compile(r"--([a-z0-9-]+)\s*:\s*([^;]+);")
HEX = re.compile(r"^#([0-9a-fA-F]{6})$")
RGBA = re.compile(r"^rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*\)$")
PX = re.compile(r"^(\d+)px$")
MS = re.compile(r"^(\d+)ms$")


def parse(css_text):
    root = re.search(r":root\s*\{(.*?)\n\}", css_text, re.S).group(1)
    colours, px, ms = {}, {}, {}
    for name, raw in VAR.findall(root):
        raw = raw.strip()
        m = HEX.match(raw)
        if m:
            colours[name] = (int(m.group(1), 16) << 8) | 0xFF
            continue
        m = RGBA.match(raw)
        if m:
            r, g, b = (int(m.group(i)) for i in (1, 2, 3))
            colours[name] = (r << 24) | (g << 16) | (b << 8) | round(float(m.group(4)) * 255)
            continue
        m = PX.match(raw)
        if m:
            px[name] = int(m.group(1))
            continue
        m = MS.match(raw)
        if m:
            ms[name] = int(m.group(1))
    return dict(colours=colours, px=px, ms=ms)


def cname(prefix, name):
    return "AT_%s_%s" % (prefix, name.upper().replace("-", "_"))


def header_text(tok):
    out = ["/* generated by menu/pipeline/atlas_tokens.py from the Atlas tokens.css: do not edit */",
           "#ifndef GW_UI_TOKENS_H", "#define GW_UI_TOKENS_H", ""]
    for name, v in tok["colours"].items():
        out.append("#define %s 0x%08Xu" % (cname("C", name), v))
    out.append("")
    for name, v in tok["px"].items():
        out.append("#define %s %d" % (cname("PX", name), v))
    out.append("")
    for name, v in tok["ms"].items():
        out.append("#define %s %d" % (cname("MS", name[2:] if name.startswith("m-") else name), v))
    out += ["", "#endif", ""]
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--header", default=DEFAULT_HEADER)
    a = ap.parse_args(argv)
    tok = parse(open(SRC, encoding="utf-8").read())
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    with open(OUT_JSON, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(dict(source=os.path.relpath(SRC, ROOT).replace("\\", "/"), **tok), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(a.header, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(header_text(tok))
    print("tokens: %d colours, %d sizes, %d timings -> %s, %s"
          % (len(tok["colours"]), len(tok["px"]), len(tok["ms"]), OUT_JSON, a.header))
    return 0


if __name__ == "__main__":
    sys.exit(main())
