"""Tests for atlas_tokens.py: python menu/pipeline/test_atlas_tokens.py"""
import os
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import atlas_tokens as T  # noqa: E402


class Tokens(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tok = T.parse(open(T.SRC, encoding="utf-8").read())

    def test_colours(self):
        c = self.tok["colours"]
        self.assertEqual(c["ember"], 0xFF7A3DFF)
        self.assertEqual(c["jade"], 0x4FD6AAFF)
        self.assertEqual(c["plate"], 0x1A1F29FF)
        self.assertEqual(c["scrim"], 0x05070AB8)  # rgba(5,7,10,.72)
        self.assertEqual(c["p4"], 0x42D68BFF)

    def test_sizes(self):
        p = self.tok["px"]
        self.assertEqual([p["t-cap"], p["t-body"], p["t-row"], p["t-label"], p["t-title"], p["t-hero"], p["t-display"]],
                         [12, 14, 16, 20, 28, 44, 64])
        self.assertEqual([p["ch"], p["ch-s"], p["ch-xs"]], [8, 5, 3])
        self.assertEqual([p["s1"], p["s2"], p["s3"], p["s4"], p["s5"]], [4, 8, 12, 16, 24])

    def test_motion(self):
        m = self.tok["ms"]
        self.assertEqual([m["m-focus"], m["m-tab"], m["m-pane"], m["m-modal"], m["m-note"], m["m-turn"]],
                         [80, 120, 100, 140, 160, 12000])

    def test_names(self):
        n = T.names_text(self.tok)
        self.assertIn('{ "ember", 0xFF7A3DFFu },', n)
        self.assertIn('{ "scrim", 0x05070AB8u },', n)
        self.assertEqual(n.count('{ "'), len(self.tok["colours"]))

    def test_header_text(self):
        h = T.header_text(self.tok)
        self.assertIn("#define AT_C_EMBER 0xFF7A3DFFu", h)
        self.assertIn("#define AT_PX_T_CAP 12", h)
        self.assertIn("#define AT_MS_FOCUS 80", h)
        self.assertIn("generated by menu/pipeline/atlas_tokens.py", h)


if __name__ == "__main__":
    unittest.main()
