"""rows_doc.py - print the clip checklist tables (docs/geno-artist-rows.md) from data/clip_table.json.

    python -m tools.geno.artist clips --markdown > docs/geno-artist-rows.md
"""
from . import spec

TIERS = [("prototype", "Prototype: author these first (a fighter that idles, walks, runs, jumps, jabs, shields and grabs)"),
         ("recommended", "Recommended: the rows a first play session reaches within seconds"),
         ("finished", "Finished fighter: author these for final art"),
         ("optional", "Optional: safe to share a clip (item swings, scope, ledge variants, crazy hand...)")]


def markdown():
    t = spec.clip_table()
    out = ["# Engine motion rows by tier (generated)", "",
           "Generated by `python -m tools.geno.artist clips --markdown` from `tools/geno/artist/data/clip_table.json`. Do not edit by hand.",
           "Name an action exactly like the row to serve it. 'Falls back to' is what plays when you do not author it (the build report lists these as placeholders).",
           "'script' is the Striker move script the default move set plays on that row: its first hitbox frame and length (see the checklist, hit-frame alignment).", ""]
    for tier, title in TIERS:
        out += ["## " + title, "", "| row | loop | falls back to | script: first hit / length | notes |", "|---|---|---|---|---|"]
        for r in t["rows"]:
            if r["tier"] != tier:
                continue
            tm = r.get("timing")
            ts = ""
            if tm:
                fh = tm["first_hit_frame"]
                if fh is None and tm["release_frame"] is not None:
                    fh = "release %s" % tm["release_frame"]
                ts = "%s: %s / %s" % (tm["script"], fh if fh is not None else "-", tm["script_frames"])
            note = "ROOT MOTION" if r.get("root_motion") else ""
            if r["name"] in t["walk_run_rows"]:
                note = (note + " locomotion: measured reference speed").strip()
            out.append("| `%s` | %s | %s | %s | %s |" % (r["name"], "loop" if r.get("loop") else "once",
                                                       ", ".join("`%s`" % x for x in r.get("fallback", [])) or "`Wait`", ts, note))
        out.append("")
    out += ["## Move timing the default move set expects (hit-frame alignment)", "",
            "The default moves are the Striker's scripts. A clip's strike pose must land on the script's first hitbox frame (counted in clip frames from 0), and the clip must be at least as long as the script, or the move ends early.", "",
            "| row | script | first hitbox / release frame | script length (clip needs at least) |", "|---|---|---|---|"]
    for r in t["rows"]:
        tm = r.get("timing")
        if tm:
            out.append("| `%s` | %s | %s | %s |" % (r["name"], tm["script"], tm["first_hit_frame"] if tm["first_hit_frame"] is not None else ("release " + str(tm["release_frame"]) if tm["release_frame"] is not None else "none (no hitbox)"), tm["script_frames"]))
    out += ["", "## Root-motion rows (translation on the translation bone is kept; everything else is in place)", "",
            ", ".join("`%s`" % r["name"] for r in t["rows"] if r.get("root_motion")), ""]
    out += ["## No animation (the engine plays no clip)", "", ", ".join("`%s`" % r["name"] for r in t["rows"] if r["tier"] == "none"), ""]
    return "\n".join(out)
