"""python tools/release/launcher/gen_atlas_icons.py [--check]: atlas_icons.h from the concept's ICONS (the one source)."""
import importlib.util, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
PARTS = os.path.join(ROOT, "menu", "concepts", "reunification-2026-10-06", "c-atlas", "parts.py")
OUT = os.path.join(HERE, "qt", "atlas_icons.h")
NAMES = ["disc", "mods", "data", "check", "plus", "right", "left", "up", "down", "star", "x", "folder"]
TOK = re.compile(r"([A-Za-z])|(-?\d*\.?\d+)")     # every letter is a token, so an unsupported command is seen and refused


def load():
    spec = importlib.util.spec_from_file_location("atlas_parts", PARTS)
    m = importlib.util.module_from_spec(spec)
    sys.path.insert(0, os.path.dirname(PARTS))
    spec.loader.exec_module(m)
    return m.ICONS


def path_calls(d, name):
    toks = [(a or b) for a, b in TOK.findall(d)]
    out, i, cmd, cx, cy, sx, sy = [], 0, None, 0.0, 0.0, 0.0, 0.0

    def num():
        nonlocal i
        v = float(toks[i])
        i += 1
        return v
    while i < len(toks):
        if toks[i].isalpha():
            cmd = toks[i]
            i += 1
        elif cmd is None:
            raise ValueError("%s: path starts with a number" % name)
        c = cmd
        if c in "Zz":
            out.append("p.closeSubpath();")
            cx, cy = sx, sy
            continue
        if c in "Hh":
            x = num()
            cx = x if c == "H" else cx + x
        elif c in "Vv":
            y = num()
            cy = y if c == "V" else cy + y
        elif c in "MmLl":
            x, y = num(), num()
            cx, cy = (x, y) if c in "ML" else (cx + x, cy + y)
        else:
            raise ValueError("%s: unsupported path command %s" % (name, c))
        if c in "Mm":
            out.append("p.moveTo(%g, %g);" % (cx, cy))
            sx, sy = cx, cy
            cmd = "L" if c == "M" else "l"
        else:
            out.append("p.lineTo(%g, %g);" % (cx, cy))
    return out


def shape_calls(svg, name):
    out = []
    for tag, attrs in re.findall(r"<(circle|rect|path)\s+([^>]*?)/>", svg):
        a = dict(re.findall(r'([\w-]+)="([^"]*)"', attrs))
        if tag == "circle":
            out.append("p.addEllipse(QPointF(%s, %s), %s, %s);" % (a["cx"], a["cy"], a["r"], a["r"]))
        elif tag == "rect":
            out.append("p.addRect(%s, %s, %s, %s);" % (a["x"], a["y"], a["width"], a["height"]))
        else:
            out += path_calls(a["d"], name)
    if not out:
        raise ValueError("%s: no shape found" % name)
    return out


def render():
    icons = load()
    lines = ["// generated by tools/release/launcher/gen_atlas_icons.py from c-atlas/parts.py ICONS: do not edit", "#pragma once",
             "#include <QPainterPath>", "#include <QPointF>", "#include <QString>", "namespace launcher::kit::icons {",
             "// 24 x 24 viewBox; stroke icons: the caller strokes them 1.6 px wide in the foreground colour",
             "inline QPainterPath path(const QString &name) {", "    QPainterPath p;"]
    for n in NAMES:
        lines.append('    if (name == "%s") {' % n)
        lines += ["        " + c for c in shape_calls(icons[n], n)]
        lines.append("        return p;\n    }")
    lines += ["    return p;", "}", "}"]
    return "\n".join(lines) + "\n"


def main(argv, out=OUT):
    text = render()
    if "--check" in argv:
        return 0 if os.path.exists(out) and open(out, encoding="utf-8").read() == text else 1
    open(out, "w", encoding="utf-8", newline=chr(10)).write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
