// generated by tools/release/launcher/gen_atlas_icons.py from c-atlas/parts.py ICONS: do not edit
#pragma once
#include <QPainterPath>
#include <QPointF>
#include <QString>
namespace launcher::kit::icons {
// 24 x 24 viewBox; stroke icons: the caller strokes them 1.6 px wide in the foreground colour
inline QPainterPath path(const QString &name) {
    QPainterPath p;
    if (name == "disc") {
        p.addEllipse(QPointF(12, 12), 9, 9);
        p.addEllipse(QPointF(12, 12), 2.5, 2.5);
        return p;
    }
    if (name == "mods") {
        p.moveTo(12, 3);
        p.lineTo(20, 7.5);
        p.lineTo(20, 16.5);
        p.lineTo(12, 21);
        p.lineTo(4, 16.5);
        p.lineTo(4, 7.5);
        p.closeSubpath();
        p.moveTo(12, 12);
        p.lineTo(12, 21);
        p.moveTo(4, 7.5);
        p.lineTo(12, 12);
        p.lineTo(20, 7.5);
        return p;
    }
    if (name == "data") {
        p.moveTo(5, 6);
        p.lineTo(19, 6);
        p.moveTo(5, 12);
        p.lineTo(19, 12);
        p.moveTo(5, 18);
        p.lineTo(19, 18);
        p.addRect(3, 5, 2, 2);
        return p;
    }
    if (name == "check") {
        p.moveTo(4, 12);
        p.lineTo(9, 17);
        p.lineTo(20, 6);
        return p;
    }
    if (name == "plus") {
        p.moveTo(12, 4);
        p.lineTo(12, 20);
        p.moveTo(4, 12);
        p.lineTo(20, 12);
        return p;
    }
    if (name == "right") {
        p.moveTo(9, 5);
        p.lineTo(16, 12);
        p.lineTo(9, 19);
        return p;
    }
    if (name == "left") {
        p.moveTo(15, 5);
        p.lineTo(8, 12);
        p.lineTo(15, 19);
        return p;
    }
    if (name == "up") {
        p.moveTo(5, 15);
        p.lineTo(12, 8);
        p.lineTo(19, 15);
        return p;
    }
    if (name == "down") {
        p.moveTo(5, 9);
        p.lineTo(12, 16);
        p.lineTo(19, 9);
        return p;
    }
    if (name == "star") {
        p.moveTo(12, 3);
        p.lineTo(14.7, 9);
        p.lineTo(21, 9.6);
        p.lineTo(16.2, 13.8);
        p.lineTo(17.7, 20);
        p.lineTo(12, 16.8);
        p.lineTo(6.3, 20);
        p.lineTo(7.8, 13.8);
        p.lineTo(3, 9.6);
        p.lineTo(9.3, 9);
        p.closeSubpath();
        return p;
    }
    if (name == "x") {
        p.moveTo(5, 5);
        p.lineTo(19, 19);
        p.moveTo(19, 5);
        p.lineTo(5, 19);
        return p;
    }
    if (name == "folder") {
        p.moveTo(3, 6);
        p.lineTo(10, 6);
        p.lineTo(12, 8);
        p.lineTo(21, 8);
        p.lineTo(21, 19);
        p.lineTo(3, 19);
        p.closeSubpath();
        return p;
    }
    return p;
}
}
