#!/usr/bin/env python3
"""Stamp the game checkout with its SOURCE IDENTITY: pc/platform/gw_build_id.h.

Netplay used to compare a hash of the whole executable FILE, so a Windows PE and a Linux ELF of one
commit always refused each other. The identity the handshake compares is now

    build id = FNV( source digest , numerics fingerprint )

and this script makes the first half, the same on every platform that builds the same sources:

    sha256 over, for every simulation-relevant text file of the checkout (sorted by path):
        the path (forward slashes), a NUL, and the sha256 of the file with CRLF turned into LF

"Simulation-relevant" is everything the game is built from: src/, include/, libs/ and pc/ (the shims,
the game-world code, Geno, the default Lua scripts, gwtool's source), minus documentation, tests,
the old pipeline scripts, the generated m-ex bridge (its addresses are build-specific) and this
header itself. Files come from `git ls-files --cached --others --exclude-standard`, read from the
WORKING TREE, so a locally modified or an added source file changes the digest and two builds that
differ in what they compile refuse each other; two builds of one clean commit agree whatever the
platform, the checkout's line endings or the build directory.

What this digest cannot see is how the sources were compiled. That half is measured at run time
(gw_netplay.c, np_numerics_fingerprint): the game's own math functions and the native shims' float
arithmetic are run on fixed inputs and hashed, so a build whose floating point rounds differently
(x87 instead of SSE, another libm) gets another id and is refused, instead of desyncing mid-match.

    python tools/port/build_id.py --melee <game checkout>          write the header if it changed
    python tools/port/build_id.py --melee <game checkout> --print  print the digest, write nothing
"""
import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

ROOTS = ('src', 'include', 'libs', 'pc')
SUFFIXES = {'.c', '.cpp', '.cc', '.h', '.hpp', '.inc', '.s', '.asm', '.def', '.ld', '.lcf',
            '.json', '.lua', '.txt', '.cmake'}
# directories (prefixes) that are not part of what the game is built from
SKIP_PREFIXES = ('pc/docs/', 'pc/tests/', 'pc/build/', 'pc/tools/')
KEEP = ('pc/tools/gwtool/',)  # the retargeter decides how every float operation rounds
SKIP_FILES = {'pc/platform/gw_build_id.h', 'pc/platform/gw_mex_bridge.c', 'pc/platform/gw_mex_bridge.h'}
HEADER = 'pc/platform/gw_build_id.h'


def git(melee, *args):
    return subprocess.check_output(['git', '-C', str(melee), *args], stderr=subprocess.PIPE)


def wanted(name):
    if name in SKIP_FILES or name.split('/', 1)[0] not in ROOTS:
        return False
    if any(name.startswith(p) for p in SKIP_PREFIXES) and not any(name.startswith(k) for k in KEEP):
        return False
    return Path(name).suffix.lower() in SUFFIXES


def file_list(melee):
    try:
        names = git(melee, 'ls-files', '-z', '--cached', '--others', '--exclude-standard').decode('utf-8').split('\0')
    except (OSError, subprocess.CalledProcessError):
        names = [p.relative_to(melee).as_posix() for r in ROOTS if (melee / r).is_dir() for p in (melee / r).rglob('*')
                 if p.is_file()]
    return sorted({n for n in names if n and wanted(n)})


def source_digest(melee):
    """(hex digest, file count). Missing tracked files (deleted in the working tree) count as absent."""
    digest = hashlib.sha256()
    count = 0
    for name in file_list(melee):
        path = melee / name
        if not path.is_file():
            continue
        body = path.read_bytes().replace(b'\r\n', b'\n')
        digest.update(name.encode('utf-8') + b'\0' + hashlib.sha256(body).digest())
        count += 1
    return digest.hexdigest(), count


def describe(melee):
    try:
        commit = git(melee, 'rev-parse', '--short=9', 'HEAD').decode().strip()
        dirty = bool(git(melee, 'status', '--porcelain', '--untracked-files=normal', '--', *ROOTS).strip())
        # the generated bridge and this header are always "modified" after a build: ignore them
        if dirty:
            lines = git(melee, 'status', '--porcelain', '--untracked-files=normal', '--', *ROOTS).decode().splitlines()
            dirty = any(wanted(line[3:].strip().strip('"').replace('\\', '/')) for line in lines)
        return commit + ('+local' if dirty else '')
    except (OSError, subprocess.CalledProcessError):
        return 'nogit'


def render(melee):
    digest, count = source_digest(melee)
    value = int(digest[:16], 16) or 1
    return digest, (
        '/* generated by tools/port/build_id.py: the source identity netplay compares (pc/platform/gw_netplay.c).\n'
        ' * Not committed; rewritten (only when it changes) by tools/port/build.sh and build_linux.sh. */\n'
        '#define GW_BUILD_SOURCE_HASH 0x%016xull\n'
        '#define GW_BUILD_SOURCE_DESC "%s"\n'
        '#define GW_BUILD_SOURCE_FILES %d\n' % (value, describe(melee), count))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--melee', type=Path, required=True)
    ap.add_argument('--print', action='store_true', help='print the digest and write nothing')
    args = ap.parse_args(argv)
    melee = args.melee.resolve()
    if not (melee / 'pc/platform').is_dir():
        sys.exit('error: %s is not a melee checkout' % melee)
    digest, text = render(melee)
    if args.print:
        print(digest)
        print(text, end='')
        return 0
    out = melee / HEADER
    old = out.read_text(encoding='utf-8') if out.is_file() else None
    if old != text:
        out.write_text(text, encoding='utf-8', newline='\n')
        print('build id  %s %s' % (text.splitlines()[2].split()[-1], text.splitlines()[4].split(' ', 2)[2]))
    else:
        print('build id  unchanged (%s)' % text.splitlines()[4].split(' ', 2)[2])
    return 0


if __name__ == '__main__':
    sys.exit(main())
