"""Bundle Envoy plus the unchanged mission runtime into one sandbox entry.

No mission module is copied to an editable Envoy source tree. Rebuild this
entry whenever Envoy or the shared mission runtime changes.
"""
import argparse
import ast
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MISSIONS = ROOT / 'melee/pc/scripts/examples/missions/scripts'
SCRIPTS = ROOT / 'melee/pc/scripts/examples/envoy/scripts'
TARGET = SCRIPTS / 'main.lua'
GRID = ROOT / 'melee/pc/scripts/examples/demos/grid-inventory/scripts/grid.lua'
DRIVE = SCRIPTS.parent / 'items/drive/item.json'
def mission_modules():
    # The shared runtime owns its factory order, including newly split modules.
    tree=ast.parse((ROOT/'tools/port/missions_bundle.py').read_text(encoding='utf-8'))
    for node in tree.body:
        if isinstance(node,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='MODULES' for t in node.targets):
            return ast.literal_eval(node.value)
    raise ValueError('Shared mission module list missing')

MISSION_MODULES = mission_modules()
ENVOY_MODULES = ('mod_progression', 'mod_echo', 'mod_registry', 'mod_status', 'mod_schema', 'mod_codec', 'mod_budget', 'mod_engine', 'keystones', 'mod_pool', 'mod_display', 'mod_echo_lab', 'mod_lab', 'genetics', 'companion', 'save', 'drives', 'mission_events', 'drive_models', 'fighter', 'campaign', 'run', 'classic', 'hud', 'menu', 'menu_draw', 'menu_input', 'recolour', 'visual', 'hub', 'retail_app', 'app', 'mod_synergy', 'drive_loot', 'drive_merge', 'drive_economy', 'drive_bag', 'drive_drop', 'drive_menu', 'drive_text', 'drive_lab', 'foe_roll', 'foe_lab', 'grid', 'run_screen', 'run_hud', 'run_host')


def bundle():
    lines = ['-- Generated by tools/port/envoy_bundle.py; edit source modules.', 'local missions = {}']
    for name in MISSION_MODULES:
        literal = json.dumps((MISSIONS / (name + '.lua')).read_text(encoding='utf-8'), ensure_ascii=False)
        suffix = '' if name == 'mission' else '(missions)'
        lines.append(f'missions.{name} = assert(load({literal}, "@missions/{name}.lua", "t"))(){suffix}')
    lines.append('missions.mission_launch = nil -- Envoy owns explicit scene/run launch; no standalone autostart.')
    lines.append('local envoy = {loader=missions.loader, maze_set=missions.maze_set, maze=missions.maze}')
    juice = (ROOT / 'melee/pc/scripts/lib/pickup_juice.lua').read_text(encoding='utf-8')
    lines.append(f'envoy.pickup_juice = assert(load({json.dumps(juice, ensure_ascii=False)}, "@lib/pickup_juice.lua", "t"))()')
    for name in ENVOY_MODULES:
        source = (GRID if name == 'grid' else SCRIPTS / (name + '.lua')).read_text(encoding='utf-8')
        if name == 'grid': source = 'return function(D)'+chr(10)+source+chr(10)+'end'+chr(10)  # the demo component, embedded unedited
        literal = json.dumps(source, ensure_ascii=False)
        lines.append(f'envoy.{name} = assert(load({literal}, "@envoy/{name}.lua", "t"))()(envoy)')
    lines += ['local mission = missions.runtime.new(envoy.mission_events.engine(gd))',
              'local app = envoy.app.new(gd, mission)',
              'local mods = envoy.mod_lab.new(gd,{blocked=function() return app.run.active or (app.retail and app.retail.active) or app.mission.current~=nil end,run_host=function() return app.retail~=nil and app.retail.active==true and app.retail.rules==true end,run_ready=function() return app.retail.host~=nil and app.retail.host:ready() end,activate=function() app.visible=false;app.input:close() end})',
              'app.retail.host = envoy.run_host.new(gd,mods,app.retail)',
              'app.retire = function() missions.install.retire(mission) end',
              'app.detach_events = envoy.mission_events.observe(missions.mission, function(e) app:mission_event(e) end, gd.log)',
              'function on_frame() local handled=mods:frame();if not handled or mods:hosted() then app:frame() end end',
              'function on_tick() local menu=mods:tick();if not menu or mods:hosted() then app:tick() end;if app.retail.host then app.retail.host:tick() end end',
              'function on_draw() app:draw();mods:draw();app.retail.host:draw() end',
              'function on_enemy_defeated(event) app:defeated(event) end',
              'function on_item_collect(event) app:item_collect(event);mods:pickup(event) end',
              'function on_item_expire(event) app:item_expire(event);mods:pickup_expire(event) end',
              'function on_match_start() app:match_start();mods:scene() end',
              'function on_match_end() app:match_end();mods:scene() end',
              'function on_1p_stage_start(e) app:retail_event("stage_start",e) end',
              'function on_1p_spawn(e) app:retail_event("spawn",e) end',
              'function on_1p_stage_clear(e) app:retail_event("stage_clear",e) end',
              'function on_1p_boss_defeated(e) app:retail_event("boss_defeated",e) end',
              'function on_1p_game_over(e) app:retail_event("game_over",e) end',
              'function on_1p_complete(e) app:retail_event("complete",e) end',
              'function on_unload() mods:unload();app:unload() end',
              'function on_loadstate() if not gd.sim_read or not gd.sim_read() then app:stop("quit") end;mods:loadstate() end',
              'function on_scene() mods:scene() end',
              'function on_hit(a,b,e) mods:hit(a,b,e) end',
              'function on_ko(a,b) mods:ko(a,b) end',
              'function on_stock_lost(p) mods:stock_lost(p) end',
              'function on_land(p,m,s) mods:action("landing",p,m,s) end',
              'function on_jump(p,m,s) mods:action("jump",p,m,s) end',
              'function on_air_jump(p,m,s) mods:action("air_jump",p,m,s) end',
              'function on_ledge_grab(p,m,s) mods:action("ledge_grab",p,m,s) end',
              'function on_grab(p,m,s) mods:action("grab",p,m,s) end',
              'function on_throw(p,m,s) mods:action("throw",p,m,s) end',
              'function on_taunt(p,m,s) mods:action("taunt",p,m,s) end',
              'function on_shield_hit(p,m,s) mods:action("shield_hit",p,m,s) end',
              'function on_perfect_shield(p,m,s) mods:action("perfect_shield",p,m,s) end',
              'function on_clank(e) mods:clank(e) end']
    return '\n'.join(lines) + '\n'


def drive_definition(tuning=None):
    tuning=tuning if tuning is not None else (SCRIPTS/'companion.lua').read_text(encoding='utf-8')
    match=re.search(r'\bpickup_base\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*[,}]',tuning)
    if not match: raise ValueError('pickup_base must be a positive numeric tuning literal')
    radius=float(match[1]);definition=json.loads(DRIVE.read_text(encoding='utf-8'))
    scale=definition['visual']['scale']
    if not isinstance(scale,(int,float)) or not math.isfinite(scale) or scale<=0 or not math.isfinite(radius) or radius<=0:
        raise ValueError('Fixed pickup radius and visual scale must be finite and positive')
    definition['radius']=radius/scale
    return definition


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = bundle();definition=drive_definition()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding='utf-8') != text:
            parser.exit(1, 'Envoy bundle stale; run tools/port/envoy_bundle.py\n')
        if json.loads(DRIVE.read_text(encoding='utf-8')) != definition:
            parser.exit(1, 'Envoy fixed radius stale; run tools/port/envoy_bundle.py\n')
    else:
        if json.loads(DRIVE.read_text(encoding='utf-8')) != definition:
            DRIVE.write_bytes((json.dumps(definition,indent=2)+'\n').encode('utf-8'))
        TARGET.write_bytes(text.encode('utf-8'))


if __name__ == '__main__':
    main()
