"""Deterministic single-entry bundle. Modules stay readable and below 400 lines.

The engine exposes load but not require. Escaped text preserves module line
numbers, while keeping the generated entry short and top-level locals bounded.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / 'melee/pc/scripts/examples/missions/scripts'
MODULES = ('mission', 'validator', 'maze_set', 'maze_clearance', 'maze_metrics', 'maze_topology', 'maze_check', 'maze_world_check', 'maze_route', 'maze_encounters', 'maze', 'maze_world', 'loader', 'world', 'zones', 'chunks', 'glue', 'fighters', 'camera', 'maze_commands', 'maze_rewards', 'world_commands', 'commands', 'mission_finish', 'hud', 'mission_warm', 'install', 'mission_launch', 'runtime')


def bundle():
    lines = ['-- Generated by tools/port/missions_bundle.py; edit the source modules.', 'local modules = {}']
    for name in MODULES:
        source = (SCRIPTS / (name + '.lua')).read_text(encoding='utf-8')
        literal = json.dumps(source, ensure_ascii=False)
        suffix = '' if name == 'mission' else '(modules)'
        lines.append(f'modules.{name} = assert(load({literal}, "@missions/{name}.lua", "t"))(){suffix}')
    lines += ['local runtime = modules.runtime.new(gd)',
              'function on_launch(request) runtime:launch_start(request) end',
              'function on_tick() runtime:tick() end',
              'function on_frame_pre() runtime:pre_frame() end',
              'function on_match_start() if not runtime.guarded then runtime:match_start() end end',
              'function on_frame() runtime:frame() end',
              'function on_draw() runtime:draw() end',
              'function on_match_end() runtime:stop("match end") end',
              'function on_unload() runtime:stop("unload") end',
              'function on_loadstate() runtime:stop("state load unsupported") end']
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = bundle()
    target = SCRIPTS / 'main.lua'
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8') != text:
            parser.exit(1, 'missions bundle stale; run tools/port/missions_bundle.py\n')
    else:
        target.write_bytes(text.encode('utf-8'))


if __name__ == '__main__':
    main()
