"""Generate pc/tests/atlas_settings_tables.inc from the FrontendItem tables of the settings pages.

    python tools/port/settings_descriptors.py --write | --check

Each table becomes a copy of itself with the REAL labels, help text, ranges, steps, option strings, reasons and groups, and a stand-in for every function
pointer the row has (gen_get, gen_set, gen_fmt, gen_vis, gen_call, gen_en: defined by the test). The native test (pc/tests/atlas_settings_test.c) runs the real
table walker and the real settings host over them, so the pages are checked from the real tables' shapes without the game. The real getters and setters are
proved in the game (the checklist in the plan's Task 11).

The parser reads the C text: positional initialisers, strings with commas and adjacent literals, `static const char* const` option arrays across the
three source files. A table it cannot read stops the generator with the table's name: a parser fault is never data.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GAME = os.environ.get("GW_MELEE") or os.path.join(ROOT, "melee")
GM = os.path.join(GAME, "src", "melee", "gm")
OUT = os.path.join(GAME, "pc", "tests", "atlas_settings_tables.inc")
FILES = ("gmfrontend_settings.inc", "gmfrontend_controls.inc", "gmfrontend.c")
TABLE = re.compile(r"static const FrontendItem (\w+)\[\] = \{(.*?)\n\};", re.S)
STRARR = re.compile(r"static const char\* const (\w+)\[\] = \{(.*?)\};", re.S)
STRLIT = re.compile(r'"(?:[^"\\]|\\.)*"')
FIELDS = ("kind", "action", "label", "help", "get", "set", "min", "max", "step", "options", "format", "visible", "call", "enabled", "off_reason", "group")
FPTR = {"get": "gen_get", "set": "gen_set", "format": "gen_fmt", "visible": "gen_vis", "call": "gen_call", "enabled": "gen_en"}


def split_top(s):
    """Split on commas that are not inside a string, parentheses or braces."""
    out, depth, cur, q = [], 0, [], False
    i = 0
    while i < len(s):
        c = s[i]
        if q:
            cur.append(c)
            if c == "\\":
                i += 1
                cur.append(s[i])
            elif c == '"':
                q = False
        elif c == '"':
            q = True
            cur.append(c)
        elif c in "({":
            depth += 1
            cur.append(c)
        elif c in ")}":
            depth -= 1
            cur.append(c)
        elif c == "," and depth == 0:
            out.append("".join(cur).strip())
            cur = []
        else:
            cur.append(c)
        i += 1
    tail = "".join(cur).strip()
    if tail:
        out.append(tail)
    return out


def strip_comments(s):
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    return re.sub(r"//[^\n]*", "", s)


def literal(field):
    """A C string literal field (possibly several adjacent literals) as one line, or None for NULL / 0 / absent."""
    parts = STRLIT.findall(field)
    if not parts:
        return None
    return " ".join(parts)


def row_items(body):
    """The top-level brace groups of a table body."""
    depth, start, items = 0, None, []
    q = False
    i = 0
    while i < len(body):
        c = body[i]
        if q:
            if c == "\\":
                i += 1
            elif c == '"':
                q = False
        elif c == '"':
            q = True
        elif c == "{":
            if depth == 0:
                start = i + 1
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0 and start is not None:
                items.append(body[start:i])
        i += 1
    return items


def read_sources():
    texts = {}
    for name in FILES:
        with open(os.path.join(GM, name), encoding="utf-8", errors="replace") as f:
            texts[name] = f.read()
    return texts


def build():
    texts = read_sources()
    arrays = {}
    for name in FILES:
        for m in STRARR.finditer(texts[name]):
            elems = split_top(strip_comments(m.group(2)))
            arrays[m.group(1)] = [literal(e) for e in elems]
    lines = ["/* generated by tools/port/settings_descriptors.py from the FrontendItem tables: do not edit (python tools/port/settings_descriptors.py --write) */"]
    names = []
    opt_counts = {}
    for name in FILES:
        for m in TABLE.finditer(texts[name]):
            tname = m.group(1)
            rows, opts_out, counts = [], [], []
            for ri, raw in enumerate(row_items(m.group(2))):
                f = split_top(strip_comments(raw))
                if not f or not f[0].startswith("FE_"):
                    continue
                if len(f) > len(FIELDS):
                    sys.exit("settings_descriptors: %s row %d has %d fields (a table row has at most %d)" % (tname, ri, len(f), len(FIELDS)))
                f += ["0"] * (len(FIELDS) - len(f))
                d = dict(zip(FIELDS, f))
                n_opts = 0
                opt_name = "NULL"
                if re.match(r"\w+$", d["options"]) and d["options"] not in ("0", "NULL"):
                    if d["options"] not in arrays:
                        sys.exit("settings_descriptors: %s row %d: options array %s not found" % (tname, ri, d["options"]))
                    elems = arrays[d["options"]]
                    if any(e is None for e in elems):
                        sys.exit("settings_descriptors: %s: options array %s holds a non-literal" % (tname, d["options"]))
                    n_opts = len(elems)
                    opt_name = "opts_%s_%d" % (tname, ri)
                    opts_out.append("static const char *const %s[] = { %s };" % (opt_name, ", ".join(elems)))
                    if d["kind"] == "FE_CHOICE":
                        lo, hi = int(d["min"], 0), int(d["max"], 0)
                        if n_opts != hi - lo + 1:
                            sys.exit("settings_descriptors: %s row %d: %d options for the range %d..%d" % (tname, ri, n_opts, lo, hi))
                label, help_ = literal(d["label"]), literal(d["help"])
                if label is None:
                    sys.exit("settings_descriptors: %s row %d has no label literal" % (tname, ri))
                cells = [d["kind"], d["action"] if d["action"] != "0" else "0", label, help_ or "NULL", None, None, d["min"], d["max"], d["step"] or "0", opt_name]
                cells[4] = FPTR["get"] if d["get"] not in ("0", "NULL") else "NULL"
                cells[5] = FPTR["set"] if d["set"] not in ("0", "NULL") else "NULL"
                tail = [FPTR[k] if d[k] not in ("0", "NULL") else "NULL" for k in ("format", "visible", "call", "enabled")]
                tail += [literal(d["off_reason"]) or "NULL", literal(d["group"]) or "NULL"]
                rows.append("    { " + ", ".join(cells + tail) + " },")
                counts.append(n_opts)
            lines += opts_out
            lines.append("static const FrontendItem tbl_%s[] = {" % tname)
            lines += rows
            lines.append("};")
            lines.append("static const int nopts_%s[] = { %s };" % (tname, ", ".join(str(c) for c in counts)))
            names.append((tname, len(rows)))
            opt_counts[tname] = counts
    lines.append("static const StubTable all_tables[] = {")
    for n, c in names:
        lines.append('    { "%s", tbl_%s, %d, nopts_%s },' % (n, n, c, n))
    lines.append("};")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    text = build()
    if a.write:
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote", OUT)
        return 0
    with open(OUT, encoding="utf-8", newline="") as f:
        have = f.read().replace("\r\n", "\n")
    if have != text:
        print("settings_descriptors: out of date; run --write and review the diff")
        return 1
    print("settings_descriptors: up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
