#!/usr/bin/env python3
"""Compare a Geno LAB export with hitboxes compiled from an Ultimate ACMD dump.

    python ports/ir/tools/framedata_check.py
    python ports/ir/tools/framedata_check.py --self-test

Defaults target Sora (Ultimate fighter id ``trail``). Only common Attack* states are
converted by acmd_to_ftcmd. LAB input chains and Geno specials are listed as
unmapped; they are generated by different tools. LAB exports contain no hitbox
offsets, so expected offsets are retained in JSON but cannot be compared.
"""
import argparse
from collections import Counter
from functools import lru_cache
import json
import struct
import math
from pathlib import Path
import re

import acmd_parse as AP
import acmd_to_ftcmd as FT
import plan_parts


ROOT = Path(__file__).resolve().parents[3]
SORA_EXPORT = ROOT / "_build/agents/alpha/runs/alpha-fd-sora/scripts-data/geno-lab_lab/framedata/ultimate_sora/v1"
MARTH_EXPORT = ROOT / "_build/agents/alpha/runs/alpha-fd-marth/scripts-data/geno-lab_lab/framedata/marth/v1"
SORA_DUMP = Path("C:/Users/Gurek/ghidra-projects/sora_acmd")
SORA_IR = ROOT / "_build/tmp/ir/trail.ultimate-body.ir.json"
OUTPUT = ROOT / "_build/tmp/sora-framedata-check.md"
FIELDS = ("start", "end", "damage", "angle", "kbg", "bkb", "radius", "bone")


def windows(text):
    if not text:
        return []
    result = []
    for part in text.split():
        if not re.fullmatch(r"\d+(?:-\d+)?", part):
            raise ValueError(f"invalid LAB hitbox frames: {text!r}")
        a, _, b = part.partition("-")
        start, end = int(a), int(b or a)
        if end < start:
            raise ValueError(f"reversed LAB hitbox frames: {text!r}")
        result.append((start, end))
    return result


def load_export(path):
    """Read the same framedata.json as pc/geno/tools/framedata_diff.py."""
    path = Path(path)
    if path.is_dir():
        path = path / "framedata.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data.get("moves"), list):
        raise ValueError(f"{path}: expected a moves array")
    for move in data["moves"]:
        if not isinstance(move.get("name"), str) or not isinstance(move.get("hitboxes"), list):
            raise ValueError(f"{path}: invalid move")
        for hb in move["hitboxes"]:
            hb["windows"] = windows(hb.get("frames", ""))
    return data


def script_for_state(name):
    """Use the converter's Melee row map, including the straight-angle row spelling."""
    if not name.startswith("Attack"):
        return None
    if name in FT.ROWS:
        return FT.ROWS[name]
    if name in ("AttackS3S", "AttackS4S"):
        return FT.ROWS[name.replace("S3S", "S3").replace("S4S", "S4")]
    return None


def signed16(value):
    return value - 65536 if value & 32768 else value


def game_frame_of(row):
    """Map ftcmd animation frames to observed frames under FT_MOTION_RATE."""
    changes = sorted((max(1, c["frame"]), float(c["args"][0]))
                     for c in row["commands"]
                     if c["cmd"] == "FT_MOTION_RATE" and FT.default_path(c.get("when", []))
                     and c.get("args") and isinstance(c["args"][0], (int, float))
                     and c["args"][0] > 0)

    def game_frame(frame):
        frame = max(1, frame)
        game, last, rate = 1.0, 1.0, 1.0
        for at, new_rate in changes:
            if at > frame:
                break
            game += (at - last) / rate
            last, rate = at, new_rate
        game += (frame - last) / rate
        return math.ceil(game - 1e-9)

    return game_frame


def expected_from_row(row, joint_of_bone, scale, *, allowlist=None):
    """Decode the actual converter output, so its quantization and fallbacks apply."""
    words, conversion = FT.translate(row, joint_of_bone, scale, allowlist=allowlist)
    game_frame = game_frame_of(row)
    active = {}
    hitboxes = []
    frame = 0
    iasa = None

    def finish(slot, end):
        hb = active.pop(slot, None)
        if hb is not None:
            hb["end"] = None if end is None else max(hb["start"], end)
            hitboxes.append(hb)

    i = 0
    while i < len(words):
        word = words[i]
        op = word >> 26
        if op == 2:  # AsyncWait frame
            frame = word & 0x3FFFFFF
        elif op == 11:  # five-word hitbox
            w1, w2, w3, w4 = words[i + 1:i + 5]
            slot = (word >> 23) & 7
            start = game_frame(frame)
            finish(slot, start - 1)
            active[slot] = {
                "id": slot, "start": start, "end": None,
                "damage": word & 0x3FF, "angle": (w3 >> 23) & 0x1FF,
                "kbg": (w3 >> 14) & 0x1FF, "bkb": (w4 >> 23) & 0x1FF,
                "radius": ((w1 >> 16) & 0xFFFF) / 256,
                "bone": (word >> 11) & 0xFF,
                "offset": [signed16(w1 & 0xFFFF) / 256,
                           signed16((w2 >> 16) & 0xFFFF) / 256,
                           signed16(w2 & 0xFFFF) / 256],
            }
            i += 4
        elif op == 15:  # RemoveHitbox
            finish(word & 0x3FFFFFF, game_frame(frame) - 1)
        elif op == 16:  # ClearHitboxes
            for slot in list(active):
                finish(slot, game_frame(frame) - 1)
        elif op == 23:  # IASA
            iasa = game_frame(frame)
        elif op == 34:  # throw data
            i += 2
        elif op == 59:
            sub = (word >> 20) & 63
            if sub == 0x3A and i + 1 < len(words):
                damage = struct.unpack(">f", struct.pack(">I", words[i + 1]))[0]
                mask = (word >> 8) & 0xFF
                for slot in active:
                    if mask & (1 << slot):
                        active[slot]["damage"] = round(damage, 5)
            i += ((word >> 16) & 15) - 1
        i += 1
    for slot in list(active):
        finish(slot, None)
    # LAB joins adjacent observations of an unchanged slot into one window.
    # It does not export position, so an offset-only update is joined too;
    # preserve every converted offset in JSON for later inspection.
    joined = []
    for hb in sorted(hitboxes, key=lambda h: (h["id"], h["start"])):
        prev = joined[-1] if joined else None
        visible = ("id", "damage", "angle", "kbg", "bkb", "radius", "bone")
        if prev is not None and prev["id"] == hb["id"] and prev["end"] is not None \
                and prev["end"] + 1 == hb["start"] \
                and all(prev[key] == hb[key] for key in visible):
            prev["end"] = hb["end"]
            prev.setdefault("offsets", [prev["offset"]]).append(hb["offset"])
        else:
            joined.append(hb)
    joined.sort(key=lambda h: (h["start"], h["id"], h["end"] or 0))
    return {"iasa": iasa, "hitboxes": joined, "conversion": conversion}


def source_rows(dump, fighter, ir, scripts):
    """Parse registered fighter game scripts directly from our Ghidra ACMD dump."""
    dump, ir = Path(dump), Path(ir)
    skeleton = plan_parts.plan(json.loads(ir.read_text(encoding="utf-8")))
    joint_of = {j["name"].lower(): i for i, j in enumerate(skeleton["joints"])}
    joint_of["top"] = 0
    agents, names = AP.name_tables(fighter)
    hash_names = dict(names)
    for name in joint_of:
        hash_names[AP.hash40(name)] = name
    for attr in FT.ELEM:
        hash_names[AP.hash40(attr)] = attr
    nro = AP.Nro(Path(AP.TOOL) / "workspace/extracted/prebuilt/nro/release" / f"lua2cpp_{fighter}.nro")
    helpers = AP.helper_names(str(dump))
    motions = AP.motion_list(fighter)
    rows = {}
    for entry in AP.load_index(str(dump)):
        if entry["kind"] != "game" or entry["owner"] != "fighter" or entry["share"]:
            continue
        if agents.get(int(entry["agent_hash"], 16)) != fighter:
            continue
        name = names.get(int(entry["script_hash"], 16))
        if name not in scripts:
            continue
        path = dump / "game" / f"{entry['agent_hash']}__{entry['script_hash']}.c"
        rows[name] = {
            "script": name,
            "commands": AP.parse_body(path.read_text(encoding="utf-8"), nro, hash_names, helpers),
            "motion": motions.get(int(entry["script_hash"], 16)),
        }
    return rows, joint_of


def measured_hitboxes(move):
    out = []
    for hb in move["hitboxes"]:
        for start, end in hb["windows"]:
            out.append({"id": int(hb["id"]), "start": start, "end": end,
                        "damage": hb["damage"], "angle": hb["angle"],
                        "kbg": hb["kbg"], "bkb": hb["bkb"],
                        "radius": hb["radius"], "bone": hb["bone"],
                        "offset": None})
    return sorted(out, key=lambda h: (h["id"], h["start"], h["end"]))


def compare_hitbox(expected, measured):
    bad = []
    for field in ("start", "end"):
        if expected[field] is not None and measured[field] is not None \
                and abs(expected[field] - measured[field]) > 1:
            bad.append(field)
    if abs(expected["damage"] - measured["damage"]) > 0.5:
        bad.append("damage")
    for field in ("angle", "kbg", "bkb"):
        if expected[field] != measured[field]:
            bad.append(field)
    if abs(expected["radius"] - measured["radius"]) > 0.1 * expected["radius"] + 1e-9:
        bad.append("radius")
    if expected["bone"] != measured["bone"]:
        bad.append("bone")
    return bad


def pair_cost(a, b):
    # A moderate timing shift should still pair the same ID/payload; insertions
    # and deletions should not cascade into every later phase of a multi-hit move.
    cost = min(abs(a["start"] - b["start"]), 30) / 3
    if a["end"] is not None:
        cost += min(abs(a["end"] - b["end"]), 30) / 3
    cost += min(abs(a["damage"] - b["damage"]), 10) / 2
    cost += 2 * (a["angle"] != b["angle"])
    cost += (a["kbg"] != b["kbg"]) + (a["bkb"] != b["bkb"])
    cost += (a["bone"] != b["bone"])
    return cost


def align(expected, measured):
    """Pair hitbox phases by slot and sequence, allowing a missing phase."""
    result = []
    for slot in sorted({h["id"] for h in expected + measured}):
        a = sorted((h for h in expected if h["id"] == slot), key=lambda h: h["start"])
        b = sorted((h for h in measured if h["id"] == slot), key=lambda h: h["start"])

        @lru_cache(None)
        def solve(i, j):
            if i == len(a):
                return 6 * (len(b) - j), [(None, x) for x in b[j:]]
            if j == len(b):
                return 6 * (len(a) - i), [(x, None) for x in a[i:]]
            options = []
            cost, tail = solve(i + 1, j + 1)
            options.append((cost + pair_cost(a[i], b[j]), [(a[i], b[j])] + tail))
            cost, tail = solve(i + 1, j)
            options.append((cost + 6, [(a[i], None)] + tail))
            cost, tail = solve(i, j + 1)
            options.append((cost + 6, [(None, b[j])] + tail))
            return min(options, key=lambda x: x[0])

        result.extend(solve(0, 0)[1])
    return sorted(result, key=lambda pair: ((pair[0] or pair[1])["start"],
                                            (pair[0] or pair[1])["id"]))


def compare_move(name, script, expected, measured):
    details = []
    counts = Counter()
    a, b = expected["iasa"], measured.get("iasa")
    if a and b is not None and abs(a - b) > 1:
        counts["iasa"] += 1
        details.append({"category": "iasa", "expected": a, "measured": b,
                        "score": abs(a - b), "hitbox_id": None})
    elif a and b is None:
        counts["iasa_missing"] += 1
        details.append({"category": "iasa_missing", "expected": a, "measured": None,
                        "score": 5, "hitbox_id": None})
    elif not a and b is not None:
        counts["iasa_extra"] += 1
        details.append({"category": "iasa_extra", "expected": None, "measured": b,
                        "score": 5, "hitbox_id": None})
    measured_hb = measured_hitboxes(measured)
    for x, y in align(expected["hitboxes"], measured_hb):
        if x is None or y is None:
            category = "hitbox_extra" if x is None else "hitbox_missing"
            counts[category] += 1
            details.append({"category": category, "expected": x, "measured": y,
                            "score": 8, "hitbox_id": (x or y)["id"]})
            continue
        for category in compare_hitbox(x, y):
            counts[category] += 1
            if category == "radius":
                score = 10 * abs(x[category] - y[category]) / x[category]
            elif category in ("start", "end", "damage"):
                score = abs(x[category] - y[category])
            else:
                score = 5 if category == "bone" else 3
            details.append({"category": category, "expected": x[category],
                            "measured": y[category], "score": score,
                            "hitbox_id": x["id"], "expected_window": [x["start"], x["end"]],
                            "measured_window": [y["start"], y["end"]]})
    return {"name": name, "script": script, "status": "mismatch" if details else "match",
            "expected": expected, "measured": {"iasa": b, "hitboxes": measured_hb},
            "counts": dict(counts), "details": details}


def compare(export, rows, joint_of, scale):
    by_name = {m["name"]: m for m in export["moves"]}
    results = []
    mapped_scripts = set()
    for name, move in by_name.items():
        script = script_for_state(name)
        if script is None:
            results.append({"name": name, "script": None, "status": "unmapped",
                            "expected": None, "measured": move, "counts": {}, "details": []})
        elif script not in rows:
            results.append({"name": name, "script": script, "status": "source_missing",
                            "expected": None, "measured": move, "counts": {"source_missing": 1},
                            "details": []})
        else:
            mapped_scripts.add(script)
            results.append(compare_move(name, script,
                        expected_from_row(rows[script], joint_of, scale), move))
    for name, script in FT.ROWS.items():
        if not name.startswith("Attack") or name in by_name or script not in rows \
                or script in mapped_scripts:
            continue
        results.append({"name": name, "script": script, "status": "export_missing",
                        "expected": expected_from_row(rows[script], joint_of, scale),
                        "measured": None, "counts": {"export_missing": 1}, "details": []})
    counts = Counter()
    for result in results:
        counts.update(result["counts"])
        if result["status"] == "unmapped":
            counts["unmapped"] += 1
    worst = sorted((dict(move=r["name"], script=r["script"], **d)
                    for r in results for d in r["details"]),
                   key=lambda d: (-d["score"], d["move"], d["category"],
                                  d["hitbox_id"] if d["hitbox_id"] is not None else -1))[:10]
    return {"fighter": export["fighter"], "version": export.get("version"),
            "scale": scale, "category_counts": dict(sorted(counts.items())),
            "moves": results, "worst": worst,
            "limitations": ["LAB export does not include hitbox X/Y/Z offsets; expected offsets are recorded but cannot be checked.",
                            "Only common Attack* states use acmd_to_ftcmd. Input chains and Geno specials are unmapped."]}


def fmt(value):
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.3f}".rstrip("0").rstrip(".")
    return str(value)


def markdown(report):
    lines = [f"# {report['fighter']} frame-data check ({report['version']})", "",
             f"Unit scale: {fmt(report['scale'])}. Frame 1 is the first state frame.", "",
             "## Category counts", "", "| Category | Count |", "|---|---:|"]
    lines += [f"| {k} | {v} |" for k, v in report["category_counts"].items()]
    lines += ["", "## Moves", "", "| Move | Ultimate script | Status | Expected IASA / boxes | LAB IASA / boxes | Issues |",
              "|---|---|---|---:|---:|---|"]
    for r in report["moves"]:
        exp, got = r["expected"], r["measured"]
        e = "—" if exp is None else f"{fmt(exp['iasa'])} / {len(exp['hitboxes'])}"
        g = "—" if got is None else f"{fmt(got.get('iasa'))} / {len(got['hitboxes'])}"
        issues = ", ".join(f"{k}: {v}" for k, v in sorted(r["counts"].items())) or "—"
        lines.append(f"| {r['name']} | {r['script'] or '—'} | {r['status']} | {e} | {g} | {issues} |")
    lines += ["", "## Field mismatches", "", "| Move | Hitbox | Field | Expected | LAB |",
              "|---|---:|---|---|---|"]
    for r in report["moves"]:
        for d in r["details"]:
            x, y = d["expected"], d["measured"]
            if isinstance(x, dict):
                x = f"id {x['id']} f{x['start']}-{x['end']} {fmt(x['damage'])}% r{fmt(x['radius'])} bone {x['bone']}"
            if isinstance(y, dict):
                y = f"id {y['id']} f{y['start']}-{y['end']} {fmt(y['damage'])}% r{fmt(y['radius'])} bone {y['bone']}"
            lines.append(f"| {r['name']} | {fmt(d['hitbox_id'])} | {d['category']} | {fmt(x)} | {fmt(y)} |")
    if not any(r["details"] for r in report["moves"]):
        lines.append("| — | — | — | — | — |")
    lines += ["", "## Worst 10 discrepancies", "", "| Move | Hitbox | Category | Expected | LAB |",
              "|---|---:|---|---|---|"]
    for issue in report["worst"]:
        x, y = issue["expected"], issue["measured"]
        if isinstance(x, dict):
            x = f"f{x['start']}-{x['end']}, {fmt(x['damage'])}%, bone {x['bone']}"
        if isinstance(y, dict):
            y = f"f{y['start']}-{y['end']}, {fmt(y['damage'])}%, bone {y['bone']}"
        lines.append(f"| {issue['move']} | {fmt(issue['hitbox_id'])} | {issue['category']} | {fmt(x)} | {fmt(y)} |")
    lines += ["", "## Limits", ""] + [f"- {item}" for item in report["limitations"]]
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--export", type=Path, default=SORA_EXPORT)
    ap.add_argument("--dump", type=Path, default=SORA_DUMP)
    ap.add_argument("--fighter", default="trail")
    ap.add_argument("--ir", type=Path, default=SORA_IR)
    ap.add_argument("--scale", type=float, default=1.0)
    ap.add_argument("--output", type=Path, default=OUTPUT)
    ap.add_argument("--self-test", action="store_true", help="parse the Marth LAB export only")
    args = ap.parse_args(argv)
    if args.self_test:
        marth = load_export(MARTH_EXPORT)
        print(f"Marth export parsed: {len(marth['moves'])} moves, "
              f"{sum(len(m['hitboxes']) for m in marth['moves'])} hitboxes")
        return 0
    export = load_export(args.export)
    scripts = {script for name, script in FT.ROWS.items() if name.startswith("Attack")}
    rows, joint_of = source_rows(args.dump, args.fighter, args.ir, scripts)
    report = compare(export, rows, joint_of, args.scale)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown(report), encoding="utf-8")
    args.output.with_suffix(".json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"{len(rows)} ACMD scripts; {len(report['moves'])} move rows; "
          f"categories {report['category_counts']}")
    print(args.output)
    print(args.output.with_suffix(".json"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
