#!/usr/bin/env python3
"""Generate the guest->native bridge table for the PPC blob interpreter.

Pairs `melee/config/GALE01/symbols.txt` (guest address -> decomp symbol name) with
`_build/melee-pc.map` (gw_<name> -> native VA) so the interpreter can resolve an absolute
guest address (a `bl`/`bctrl` target or a static global) to its native `gw_` counterpart.

Output: `pc/platform/gw_mex_bridge.c` + `.h` (checked in). Each entry is {guest, native, kind}
sorted by guest address; the runtime binary-searches it. Re-run after the game relinks (the map
changes): `python3 tools/mex_port/gen_bridge.py`.

Usage: gen_bridge.py [--symbols PATH] [--map PATH]
"""
import argparse
import os
import re
import sys

SYMBOL_RE = re.compile(
    r"^\s*(?P<name>\S+)\s*=\s*\.\S+:(?P<addr>0x[0-9A-Fa-f]+)\s*;"
    r".*?type:(?P<typ>\w+).*?scope:(?P<scope>\w+)"
)
# melee-pc.map public-symbol line: " 0001:00309e40       _gw_OSReport_PrintSpaces   1030ae40 f  obj"
# (data-section lines have no `f`/`d` type letter, so it is optional)
MAP_RE = re.compile(
    r"^\s*[0-9A-Fa-f]{4}:[0-9A-Fa-f]{8}\s+"
    r"(?P<name>_[A-Za-z0-9_$@?.]+)\s+"
    r"(?P<addr>[0-9A-Fa-f]{8})\b"
)


def parse_symbols(path):
    out = {}  # name -> (addr, kind, scope)
    for line in open(path, "r", encoding="utf-8", errors="replace"):
        m = SYMBOL_RE.match(line)
        if not m:
            continue
        name = m.group("name")
        addr = int(m.group("addr"), 16)
        typ = m.group("typ")
        scope = m.group("scope")
        # A decomp symbol may be listed more than once (per section); keep the first.
        if name not in out:
            out[name] = (addr, typ, scope)
    return out


def parse_map(path):
    out = {}  # gw_name -> native addr
    for line in open(path, "r", encoding="utf-8", errors="replace"):
        m = MAP_RE.match(line)
        if not m:
            continue
        name = m.group("name")
        addr = int(m.group("addr"), 16)
        # MSVC prefixes a leading underscore; strip it to get the C symbol name.
        if name.startswith("_"):
            name = name[1:]
        if name not in out:
            out[name] = addr
    return out


def main():
    ap = argparse.ArgumentParser()
    # Derive the repo root from this script's location (tools/mex_port/gen_bridge.py) so the
    # generator works from WSL, Git Bash and cmd alike; a hardcoded /mnt/c path did not.
    repo = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    ap.add_argument("--symbols", default=os.path.join(repo, "melee/config/GALE01/symbols.txt"))
    ap.add_argument("--map", default=os.path.join(repo, "_build/melee-pc.map"))
    ap.add_argument("--out-c", default=os.path.join(repo, "melee/pc/platform/gw_mex_bridge.c"))
    ap.add_argument("--out-h", default=os.path.join(repo, "melee/pc/platform/gw_mex_bridge.h"))
    args = ap.parse_args()

    syms = parse_symbols(args.symbols)
    mp = parse_map(args.map)

    entries = []  # (guest, native, kind)
    for name, (guest, typ, scope) in syms.items():
        gw = "gw_" + name
        native = mp.get(gw)
        if native is None:
            continue
        kind = "fn" if typ == "function" else "obj"
        entries.append((guest, native, kind))

    entries.sort(key=lambda e: e[0])
    fn_count = sum(1 for e in entries if e[2] == "fn")
    obj_count = sum(1 for e in entries if e[2] == "obj")

    # Emit a header + a C file with the packed sorted table.
    hdr = """/* gw_mex_bridge.h - guest->native bridge table for the PPC blob interpreter.
 *
 * GENERATED by tools/mex_port/gen_bridge.py - do not edit by hand. Pairs symbols.txt guest
 * addresses with melee-pc.map gw_ native VAs, so the interpreter resolves absolute guest
 * addresses (bl/bctrl targets and static globals) to the port's native `gw_` code/data.
 */
#ifndef GW_MEX_BRIDGE_H
#define GW_MEX_BRIDGE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Look up a guest address. Returns the native VA, or 0 when there is no bridge entry. `kind`
 * is set to 1 for a function, 0 for a data object (may be NULL). */
uint32_t gw_mex_bridge_lookup(uint32_t guest_addr, int *kind);

/* Number of entries (for tests/diagnostics). */
uint32_t gw_mex_bridge_count(void);

#ifdef __cplusplus
}
#endif
#endif /* GW_MEX_BRIDGE_H */
"""
    with open(args.out_h, "w") as f:
        f.write(hdr)

    c_src = []
    c_src.append("/* gw_mex_bridge.c - GENERATED by tools/mex_port/gen_bridge.py - do not edit. */\n")
    c_src.append('#include "gw_mex_bridge.h"\n')
    c_src.append("#include <stddef.h>\n\n")
    c_src.append("typedef struct gw_mex_bridge_entry {\n")
    c_src.append("    uint32_t guest;\n")
    c_src.append("    uint32_t native;\n")
    c_src.append("    uint8_t  kind; /* 1 = function, 0 = data object */\n")
    c_src.append("} gw_mex_bridge_entry;\n\n")
    c_src.append("static const gw_mex_bridge_entry gw_mex_bridge_table[] = {\n")
    for guest, native, kind in entries:
        k = 1 if kind == "fn" else 0
        c_src.append("    { 0x%08Xu, 0x%08Xu, %d },\n" % (guest, native, k))
    c_src.append("};\n\n")
    c_src.append("uint32_t gw_mex_bridge_count(void)\n")
    c_src.append("{\n")
    c_src.append("    return (uint32_t)(sizeof gw_mex_bridge_table / sizeof gw_mex_bridge_table[0]);\n")
    c_src.append("}\n\n")
    c_src.append("uint32_t gw_mex_bridge_lookup(uint32_t guest_addr, int *kind)\n")
    c_src.append("{\n")
    c_src.append("    uint32_t lo = 0;\n")
    c_src.append("    uint32_t hi = gw_mex_bridge_count();\n")
    c_src.append("    if (kind != NULL) { *kind = 0; }\n")
    c_src.append("    while (lo < hi) {\n")
    c_src.append("        uint32_t mid = lo + (hi - lo) / 2;\n")
    c_src.append("        uint32_t g = gw_mex_bridge_table[mid].guest;\n")
    c_src.append("        if (g == guest_addr) {\n")
    c_src.append("            if (kind != NULL) { *kind = gw_mex_bridge_table[mid].kind; }\n")
    c_src.append("            return gw_mex_bridge_table[mid].native;\n")
    c_src.append("        }\n")
    c_src.append("        if (g < guest_addr) { lo = mid + 1; } else { hi = mid; }\n")
    c_src.append("    }\n")
    c_src.append("    return 0;\n")
    c_src.append("}\n")

    with open(args.out_c, "w") as f:
        f.write("".join(c_src))

    print("bridge: %d entries (%d functions, %d objects) -> %s" %
          (len(entries), fn_count, obj_count, args.out_c))
    return 0


if __name__ == "__main__":
    sys.exit(main())
