#!/usr/bin/env python3
"""Generate a pad script that walks one fighter through its whole moveset, plus a frame map.

The point is that a crash in an unattended run should name the MOVE, not just the character. The
pad script has no way to log anything, so this writes <out>.map.txt alongside: frame range ->
action. A fault at "retrace=1487" is then one lookup away from "that was up-B".

Two constraints come from shim_pad.c and shape everything here:
  * substickX/Y are forced to 0, so there is NO C-STICK. Smashes and aerials are stick+A, which
    means a smash is a 2-frame full-tilt flick landing on the same frame as A.
  * The script drives channel 0 only, i.e. P1. So P1 must be the fighter under test.

Usage: gen_pad_moveset.py <out.txt> [--lead 600]
"""
import sys

A, B, X, Y, Z, R = 0x100, 0x200, 0x400, 0x800, 0x10, 0x20
DU, DD = 0x8, 0x4
FULL, TILT = 100, 62   # 62 is inside the tilt threshold; 100 is a smash/full-tilt input

out, lead = sys.argv[1], 600
if "--lead" in sys.argv:
    lead = int(sys.argv[sys.argv.index("--lead") + 1])

seg = []      # (frames, buttons, sx, sy, tl, tr)
marks = []    # (start_frame, end_frame, label)
frame = 0


def do(label, *steps):
    """One named action: a list of (frames, buttons, sx, sy[, trigger]) steps."""
    global frame
    start = frame
    for s in steps:
        f, btn, sx, sy = s[0], s[1], s[2], s[3]
        tr = s[4] if len(s) > 4 else 0
        seg.append((f, btn, sx, sy, 0, tr))
        frame += f
    marks.append((start, frame, label))


def rest(f):
    global frame
    seg.append((f, 0, 0, 0, 0, 0))
    frame += f


# The lead-in is long on purpose. PADRead runs during the load too, so the script starts burning
# frames before the match does; a short lead means the first inputs land on a black screen.
do("lead-in (load + countdown)", (lead, 0, 0, 0))

do("jab 1-2-3", (3, A, 0, 0), (9, 0, 0, 0), (3, A, 0, 0), (9, 0, 0, 0), (3, A, 0, 0)); rest(45)
do("dash attack", (12, 0, FULL, 0), (3, A, FULL, 0)); rest(45)
do("ftilt", (3, A, TILT, 0)); rest(40)
do("utilt", (3, A, 0, TILT)); rest(40)
do("dtilt", (3, A, 0, -TILT)); rest(40)
do("fsmash", (2, 0, FULL, 0), (3, A, FULL, 0)); rest(55)
do("usmash", (2, 0, 0, FULL), (3, A, 0, FULL)); rest(55)
do("dsmash", (2, 0, 0, -FULL), (3, A, 0, -FULL)); rest(55)
do("grab", (3, Z, 0, 0)); rest(45)
do("shield", (30, 0, 0, 0, 200)); rest(20)
do("roll right", (4, 0, 0, 0, 200), (3, 0, FULL, 0, 200)); rest(40)
do("roll left", (4, 0, 0, 0, 200), (3, 0, -FULL, 0, 200)); rest(40)
do("spotdodge", (4, 0, 0, 0, 200), (3, 0, 0, -FULL, 200)); rest(40)

do("jump + nair", (3, X, 0, 0), (14, 0, 0, 0), (3, A, 0, 0)); rest(70)
do("jump + fair", (3, X, 0, 0), (14, 0, 0, 0), (3, A, FULL, 0)); rest(70)
do("jump + bair", (3, X, 0, 0), (14, 0, 0, 0), (3, A, -FULL, 0)); rest(70)
do("jump + uair", (3, X, 0, 0), (14, 0, 0, 0), (3, A, 0, FULL)); rest(70)
do("jump + dair", (3, X, 0, 0), (18, 0, 0, 0), (3, A, 0, -FULL)); rest(80)
do("double jump", (3, X, 0, 0), (12, 0, 0, 0), (3, X, 0, 0)); rest(70)

# Specials last on the ground, then again in the air. Up-B in particular is where the port has
# historically died (Sonic's spring), and the airborne version takes a different branch.
do("neutral B", (4, B, 0, 0)); rest(80)
do("side B", (4, B, FULL, 0)); rest(90)
do("up B", (4, B, 0, FULL)); rest(110)
do("down B", (4, B, 0, -FULL)); rest(90)
do("air neutral B", (3, X, 0, 0), (14, 0, 0, 0), (4, B, 0, 0)); rest(100)
do("air side B", (3, X, 0, 0), (14, 0, 0, 0), (4, B, FULL, 0)); rest(100)
do("air up B", (3, X, 0, 0), (14, 0, 0, 0), (4, B, 0, FULL)); rest(120)
do("air down B", (3, X, 0, 0), (14, 0, 0, 0), (4, B, 0, -FULL)); rest(120)

do("taunt", (3, DU, 0, 0)); rest(70)
do("crouch", (50, 0, 0, -FULL)); rest(20)
do("dash dance", (8, 0, FULL, 0), (8, 0, -FULL, 0), (8, 0, FULL, 0), (8, 0, -FULL, 0)); rest(40)
do("walk right", (40, 0, TILT, 0)); rest(30)
do("settle", (150, 0, 0, 0))

with open(out, "w") as f:
    f.write("# Generated by gen_pad_moveset.py - one fighter's full moveset.\n")
    f.write("# frames buttons_hex stickX stickY triggerL triggerR\n")
    for fr, btn, sx, sy, tl, tr in seg:
        f.write("%d %04X %d %d %d %d\n" % (fr, btn, sx, sy, tl, tr))

with open(out + ".map.txt", "w") as f:
    f.write("# frame ranges -> action, for reading a crash's retrace= against\n")
    for a, b, label in marks:
        f.write("%6d %6d  %s\n" % (a, b, label))

print("%s: %d segments, %d frames (%.1fs), %d actions"
      % (out, len(seg), frame, frame / 60.0, len(marks)))
