#!/usr/bin/env python3
"""Emit one pad script per MOVE TYPE, not one per fighter.

A single 33-action script is all-or-nothing: Diddy died entering a special and took the aerials,
the defensive options and everything after it down with him, so those moves stayed untested for
that fighter. Splitting by type means a fighter that cannot do specials still gets its jabs,
tilts, smashes, aerials and movement checked on the same pass.

Each unit repeats its moves TWICE. The first pass can be eaten by the match countdown or by a
move that whiffs into a bad state; a second pass through the same inputs makes a clean unit
convincing rather than lucky.

Constraints from shim_pad.c that shape all of this:
  * substickX/Y are pinned to 0, so there is no C-stick: smashes and aerials are stick+A.
  * The script drives the channels MELEE_PAD_CHANNELS names, so with "0123" all four fighters
    perform the unit at once.

Usage: gen_pad_units.py <outdir> [--lead 300]
"""
import os
import sys

A, B, X, Z = 0x100, 0x200, 0x400, 0x10
DU = 0x8
FULL, TILT = 100, 62

outdir = sys.argv[1]
lead = 300
if "--lead" in sys.argv:
    lead = int(sys.argv[sys.argv.index("--lead") + 1])
os.makedirs(outdir, exist_ok=True)


def jump(*after):
    """X, a beat to leave the ground, then the move."""
    return [(3, X, 0, 0), (14, 0, 0, 0)] + list(after)


# Each unit: name -> list of (label, steps, recovery_frames). A step is
# (frames, buttons, stickX, stickY[, triggerR]).
UNITS = {
    "jabs_tilts": [
        ("jab 1-2-3", [(3, A, 0, 0), (9, 0, 0, 0), (3, A, 0, 0), (9, 0, 0, 0), (3, A, 0, 0)], 45),
        ("dash attack", [(12, 0, FULL, 0), (3, A, FULL, 0)], 45),
        ("ftilt", [(3, A, TILT, 0)], 40),
        ("utilt", [(3, A, 0, TILT)], 40),
        ("dtilt", [(3, A, 0, -TILT)], 40),
    ],
    "smashes": [
        ("fsmash", [(2, 0, FULL, 0), (3, A, FULL, 0)], 60),
        ("usmash", [(2, 0, 0, FULL), (3, A, 0, FULL)], 60),
        ("dsmash", [(2, 0, 0, -FULL), (3, A, 0, -FULL)], 60),
    ],
    "aerials": [
        ("nair", jump((3, A, 0, 0)), 70),
        ("fair", jump((3, A, FULL, 0)), 70),
        ("bair", jump((3, A, -FULL, 0)), 70),
        ("uair", jump((3, A, 0, FULL)), 70),
        ("dair", [(3, X, 0, 0), (18, 0, 0, 0), (3, A, 0, -FULL)], 80),
    ],
    "specials": [
        ("neutral B", [(4, B, 0, 0)], 90),
        ("side B", [(4, B, FULL, 0)], 100),
        ("up B", [(4, B, 0, FULL)], 120),
        ("down B", [(4, B, 0, -FULL)], 100),
    ],
    "air_specials": [
        ("air neutral B", jump((4, B, 0, 0)), 110),
        ("air side B", jump((4, B, FULL, 0)), 110),
        ("air up B", jump((4, B, 0, FULL)), 130),
        ("air down B", jump((4, B, 0, -FULL)), 130),
    ],
    "grab_defense": [
        ("grab", [(3, Z, 0, 0)], 50),
        ("shield", [(30, 0, 0, 0, 200)], 25),
        ("roll right", [(4, 0, 0, 0, 200), (3, 0, FULL, 0, 200)], 45),
        ("roll left", [(4, 0, 0, 0, 200), (3, 0, -FULL, 0, 200)], 45),
        ("spotdodge", [(4, 0, 0, 0, 200), (3, 0, 0, -FULL, 200)], 45),
    ],
    "movement": [
        ("walk right", [(40, 0, TILT, 0)], 30),
        ("dash dance", [(8, 0, FULL, 0), (8, 0, -FULL, 0), (8, 0, FULL, 0), (8, 0, -FULL, 0)], 40),
        ("double jump", [(3, X, 0, 0), (12, 0, 0, 0), (3, X, 0, 0)], 80),
        ("crouch", [(50, 0, 0, -FULL)], 25),
        ("taunt", [(3, DU, 0, 0)], 70),
    ],
}

for name, actions in sorted(UNITS.items()):
    seg = [(lead, 0, 0, 0, 0, 0)]
    marks = []
    frame = lead
    for rep in (1, 2):
        for label, steps, recov in actions:
            start = frame
            for st in steps:
                f, btn, sx, sy = st[0], st[1], st[2], st[3]
                tr = st[4] if len(st) > 4 else 0
                seg.append((f, btn, sx, sy, 0, tr))
                frame += f
            marks.append((start, frame, "%s (pass %d)" % (label, rep)))
            seg.append((recov, 0, 0, 0, 0, 0))
            frame += recov
    seg.append((120, 0, 0, 0, 0, 0))
    frame += 120

    path = os.path.join(outdir, "unit_%s.txt" % name)
    with open(path, "w") as f:
        f.write("# %s - generated by gen_pad_units.py\n" % name)
        f.write("# frames buttons_hex stickX stickY triggerL triggerR\n")
        for fr, btn, sx, sy, tl, tr in seg:
            f.write("%d %04X %d %d %d %d\n" % (fr, btn, sx, sy, tl, tr))
    with open(path + ".map.txt", "w") as f:
        f.write("# frame ranges -> action\n")
        for a, b, label in marks:
            f.write("%6d %6d  %s\n" % (a, b, label))
    print("%-14s %5d frames (%4.1fs)  %d actions" % (name, frame, frame / 60.0, len(marks)))
